name: Deploy Flutter to Firebase Hosting
 
on:
  push:
    branches: [ master ]
    
    
jobs:
  build: 
    name: Build the web version of the Flutter app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Download flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.0.4'
      - name: Build web project
        run: flutter build web
      - name: Upload web artifact
        uses: actions/upload-artifact@master
        with:
          name: web artifacts
          path: build/web
          
  deploy:
    name: Deploy the built version to firebase hosting
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Download web artifact
        uses: actions/download-artifact@master
        with:
          name: web artifacts
          path: build/web
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${FIREBASE_SERVICE_ACCOUNT_MOVIE_APP_E505A}'
          channelId: live
          projectId: flutter-firebase-ci
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
